[package]
name = "chess"
version = "0.0.1"

[addresses]
chess = "_"

[dev-addresses]
chess = "0xCAFE"

[dependencies]
AptosFramework = { git = "https://github.com/movementlabsxyz/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "m1" }
AptosStdlib = { git = "https://github.com/movementlabsxyz/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib", rev = "m1" }

[dev-dependencies]
